name: Daily Oil Bot

on:
  schedule:
    - cron: '0 0 * * *' # รันทุกวันตอน 7 โมงเช้าไทย
  workflow_dispatch: # ปุ่มกดรันเองเพื่อทดสอบ

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests
      - name: Run Python Script
        env:
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
        run: python Botphuri.py
