name: Botphuri Gold Daily

on:
  schedule:
    - cron: '00 2 * * *'  # รันทุกวันเวลา 01:51 UTC (เท่ากับ 08:51 ไทย)
  workflow_dispatch:      # ปุ่มกดรันเองเอาไว้เทสต์

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests
      - name: Run script
        env:
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
          USER_ID: ${{ secrets.USER_ID }}
        run: python Botphuri.py
