name: Daily Oil Bot
on:
  workflow_dispatch:
  schedule:
    # เวลา 18:28 น. ของไทย คือ 11:28 น. ของเวลา UTC
    - cron: '28 11 * * *'
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests
      - name: Run Script
        env:
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
          USER_ID: ${{ secrets.USER_ID }}
        run: python Botphuri.py
